-- Seeds the first Shop product as an unpublished DRAFT.
-- Per the mission brief: price is intentionally NOT set (price_confirmed = 0),
-- no cover/preview images, no downloadable files. The Owner completes all of
-- this through the Admin UI. Publication is blocked in application code
-- until price_confirmed = 1, a cover exists, at least one file exists,
-- license_type is set, terms_acknowledged = 1, and refund_policy_summary
-- is non-empty — see src/lib/validate.ts::checkPublishReadiness.

INSERT INTO products (
  id,
  sku,
  slug,
  title,
  short_description,
  problem_solved,
  description,
  category,
  audience,
  edition,
  version,
  status,
  price_cents,
  price_confirmed,
  currency,
  license_type,
  publicly_purchasable,
  supported_formats,
  deliverables_json,
  not_included_json,
  faqs_json,
  responsible_use_text,
  refund_eligible,
  refund_policy_summary,
  terms_acknowledged,
  download_link_expiry_hours,
  max_downloads,
  created_at,
  updated_at,
  published_at
) VALUES (
  'prod_ai_ops_playbook_seed_0001',
  'SFL-AIOPS-001',
  'ai-operations-playbook-toolkit',
  'AI Operations Playbook & Toolkit',
  'Draft product — short description pending Owner finalization.',
  'Draft product — problem statement pending Owner finalization.',
  'Draft product — full description pending Owner finalization before publication.',
  'Business Operations',
  'HVAC, plumbing, electrical, and home-service businesses',
  'Standard Self-Customization Edition',
  '1.0',
  'DRAFT',
  NULL,
  0,
  'usd',
  'SINGLE_BUSINESS',
  0,
  '',
  '[]',
  '[]',
  '[]',
  'Draft product — responsible-use statement pending Owner finalization.',
  1,
  '',
  0,
  72,
  5,
  '2026-07-27T00:00:00.000Z',
  '2026-07-27T00:00:00.000Z',
  NULL
);
