import OpsLayout from "../../components/OpsLayout";
import { gold, surface, border, muted, muted2 } from "../../lib/tokens";

const CHANNELS = [
  { name: "reset_v1",              label: "Reset Channel",       tiers: ["monthly"],             invite: "+TxavuR1J1tphOGY5" },
  { name: "quick_access_v1",       label: "Quick Access",        tiers: ["monthly"],             invite: "+kLqEl4_BUE83NjFh" },
  { name: "teachings_vault_v1",    label: "Teachings Vault",     tiers: ["lite", "starter"],     invite: "+WNHBwWxk7ahjOTEx" },
  { name: "sentinel_engine_v1",    label: "Sentinel Engine",     tiers: ["pro"],                 invite: "+ECuJPOmfSwplNGIx" },
  { name: "sentinel_architect_v1", label: "Sentinel Architect",  tiers: ["oem", "licensing"],    invite: "+eqKVBpnzrmNmOWYx" },
];

const TIER_COLOR: Record<string, string> = {
  lite: "#60a5fa", monthly: "#4ade80", starter: "#c9a227",
  pro: "#a78bfa", oem: "#f97316", licensing: "#ef4444",
};

export default function OpsAccess() {
  return (
    <OpsLayout>
      <div style={{ marginBottom: "2rem" }}>
        <div style={{ fontSize: "0.7rem", color: gold, fontWeight: 700, letterSpacing: "0.12em", textTransform: "uppercase", marginBottom: "0.5rem" }}>Ops · Access</div>
        <h1 style={{ fontSize: "1.5rem", fontWeight: 800, letterSpacing: "-0.02em" }}>Channel Access Control</h1>
      </div>

      <div style={{ display: "flex", flexDirection: "column", gap: "0.75rem", marginBottom: "2rem" }}>
        {CHANNELS.map(({ name, label, tiers, invite }) => (
          <div key={name} style={{ background: surface, border: `1px solid ${border}`, borderRadius: 8, padding: "1.25rem" }}>
            <div style={{ display: "flex", justifyContent: "space-between", alignItems: "flex-start", marginBottom: "0.5rem" }}>
              <div>
                <div style={{ fontWeight: 700, marginBottom: "0.2rem" }}>{label}</div>
                <div style={{ fontFamily: "monospace", fontSize: "0.75rem", color: muted2 }}>{name}</div>
              </div>
              <div style={{ display: "flex", gap: "0.4rem", flexWrap: "wrap", justifyContent: "flex-end" }}>
                {tiers.map(t => (
                  <span key={t} style={{
                    fontSize: "0.65rem", fontWeight: 700, padding: "0.15rem 0.5rem",
                    border: `1px solid ${TIER_COLOR[t]}`, color: TIER_COLOR[t],
                    borderRadius: 2, textTransform: "uppercase", letterSpacing: "0.08em",
                  }}>
                    {t}
                  </span>
                ))}
              </div>
            </div>
            <div style={{ fontSize: "0.75rem", color: muted }}>
              Invite: <code style={{ color: gold, fontFamily: "monospace" }}>{invite}</code>
            </div>
          </div>
        ))}
      </div>

      <div style={{ background: surface, border: `1px solid ${border}`, borderLeft: `3px solid #f97316`, borderRadius: 8, padding: "1.25rem", fontSize: "0.8rem", color: muted }}>
        <strong style={{ color: "#f97316" }}>Hard rule:</strong>{" "}
        Never modify <code style={{ color: gold }}>originus/_canon/</code> in R2.
        Channel delivery is handled exclusively by <code style={{ color: gold }}>delivery_service.py</code> — do not edit this file.
      </div>
    </OpsLayout>
  );
}
